name: Test Python Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      # Run the script
      - name: Run Python script
        run: python hello.py
